# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RUN_PLAYBOOK: "uv run ansible-playbook playbooks/bench.yml {{.CLI_ARGS}}"
  DEPS_OS_ARCHLINUX: "uv hyperfine"

tasks:
  deps-os:
    status:
      - sh -c 'type -P hyperfine'
      - sh -c 'type -P uv'
    cmd: >-
      $(grep -q Archxx /etc/*release*)
      && sudo pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
      || ( echo "please manage deps manually" && exit 1)
  deps-python:
    deps: [deps-os]
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg
    cmds:
      - uv sync --frozen --quiet
    silent: true
  upgrade:
    cmds:
      - uv sync --upgrade
  lint:
    deps: [deps-python]
    cmds:
      - "uv run ansible-lint"
  deps-galaxy:
    deps: [deps-python]
    cmds:
      - "uv run ansible-galaxy install -r requirements.yml"
  bench:
    deps: [deps-galaxy]
    cmd: >-
      hyperfine --warmup 1 -r 5
      '{{.RUN_PLAYBOOK}}'
      'ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear MITOGEN_POOL_SIZE=128 {{.RUN_PLAYBOOK}}'
  mitogen-only:
    deps: [deps-galaxy]
    cmd: 'ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear MITOGEN_POOL_SIZE=128 {{.RUN_PLAYBOOK}}'
