# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RUN_PLAYBOOK: "uv run ansible-playbook playbooks/bench.yml"
  DEPS_OS_ARCHLINUX: "uv hyperfine"

tasks:
  os-deps:
    status:
      - sh -c 'type -P hyperfine'
      - sh -c 'type -P uv'
    cmd: >-
      pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
      || sudo pacman -Sy --noconfirm {{.DEPS_OS_ARCHLINUX}}
  deps:
    deps: [os-deps]
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg
    cmds:
      - uv sync --frozen --quiet
    silent: true
  upgrade:
    cmds:
      - uv sync --upgrade
  lint:
    deps: [deps]
    cmds:
      - "uv run ansible-lint"
  galaxy-deps:
    deps: [deps]
    cmds:
      - "uv run ansible-galaxy install -r requirements.yml"
  bench:
    deps: [galaxy-deps]
    cmd: >-
      hyperfine --warmup 1 -r 5
      '{{.RUN_PLAYBOOK}}'
      'ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear MITOGEN_POOL_SIZE=128 {{.RUN_PLAYBOOK}}'
  mitogen-only:
    deps: [galaxy-deps]
    cmd: 'ANSIBLE_STRATEGY=serverscom.mitogen.mitogen_linear MITOGEN_POOL_SIZE=128 {{.RUN_PLAYBOOK}}'
