- name:         Mitogen benchmark
  hosts:        benchmark_targets
  gather_facts: false
  become:       false
  vars:
    __loop_params: "{{ range(0, 200) | list }}"
    __file_mode:   "u=rw,g=,o="
  tasks:
    - name: Cheap module call
      ansible.builtin.ping:

    - name: Create temporary test directory
      ansible.builtin.tempfile:
        state:  directory
        prefix: mitogen_test_
      register: mitogen_test_directory

    - name: Show temp directory location
      ansible.builtin.debug:
        var: mitogen_test_directory.path

    - name: Create many small files
      ansible.builtin.copy:
        dest:    "{{ mitogen_test_directory.path }}/mitogen_bench_{{ item }}"
        content: "hello {{ item }}"
        mode:    "{{ __file_mode }}"
      loop: "{{ __loop_params }}"
      loop_control:
        label: "Creating {{ mitogen_test_directory.path }}/{{ item }}"

    - name: Touch config like edits
      ansible.builtin.lineinfile:
        path:   "{{ mitogen_test_directory.path }}/mitogen_bench_config"
        line:   "k{{ item }}=v{{ item }}"
        create: true
        mode:    "{{ __file_mode }}"
      loop: "{{ __loop_params }}"
      loop_control:
        label: "Insering k{{ item }}=v{{ item }} into {{ mitogen_test_directory.path }}/mitogen_bench_config"

    - name: Cleanup file by file | long way
      ansible.builtin.file:
        path:  "{{ mitogen_test_directory.path }}/mitogen_bench_{{ item }}"
        state: absent
      loop: "{{ __loop_params }}"
      loop_control:
        label: "Removing {{ mitogen_test_directory.path }}/mitogen_bench_{{ item }}"
    - name: Cleanup config
      ansible.builtin.file:
        path:   "{{ mitogen_test_directory.path }}/mitogen_bench_config"
        state: absent
    - name: Cleanup | Final
      ansible.builtin.file:
        path:  "{{ mitogen_test_directory.path }}"
        state: absent
